// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCArNp9zrzErkeuwMgG-_wPxlKcWZsyn1g',
    appId: '1:981132399209:web:792ac46f48a77e896e88f8',
    messagingSenderId: '981132399209',
    projectId: 'schedly-e625d',
    authDomain: 'schedly-e625d.firebaseapp.com',
    storageBucket: 'schedly-e625d.firebasestorage.app',
    measurementId: 'G-HZQ5GZE5T2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTDHdp4zNYZO_iXQA5TMg48vBhIjYbcYk',
    appId: '1:981132399209:android:2c797317ec09ae7f6e88f8',
    messagingSenderId: '981132399209',
    projectId: 'schedly-e625d',
    storageBucket: 'schedly-e625d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYNBgYXS0maUTFpsx9YlbZwbihnbkRrOw',
    appId: '1:981132399209:ios:5d158d5ddd339ece6e88f8',
    messagingSenderId: '981132399209',
    projectId: 'schedly-e625d',
    storageBucket: 'schedly-e625d.firebasestorage.app',
    iosBundleId: 'com.example.schedly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYNBgYXS0maUTFpsx9YlbZwbihnbkRrOw',
    appId: '1:981132399209:ios:5d158d5ddd339ece6e88f8',
    messagingSenderId: '981132399209',
    projectId: 'schedly-e625d',
    storageBucket: 'schedly-e625d.firebasestorage.app',
    iosBundleId: 'com.example.schedly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCArNp9zrzErkeuwMgG-_wPxlKcWZsyn1g',
    appId: '1:981132399209:web:33007ab6500c98ee6e88f8',
    messagingSenderId: '981132399209',
    projectId: 'schedly-e625d',
    authDomain: 'schedly-e625d.firebaseapp.com',
    storageBucket: 'schedly-e625d.firebasestorage.app',
    measurementId: 'G-7C37E0BB8S',
  );
}
