// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvHene63scD_yzJiR0HHWHBKTad-n-sSI',
    appId: '1:1044389536762:web:8b8c7ec25645328411ba43',
    messagingSenderId: '1044389536762',
    projectId: 'schedly-production',
    authDomain: 'schedly-production.firebaseapp.com',
    storageBucket: 'schedly-production.firebasestorage.app',
    measurementId: 'G-RKCNHWHVX9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYKdbBnmvB5Bl5_f-KHNyGPbm7n-bxBgU',
    appId: '1:1044389536762:android:0a81b56a4181437311ba43',
    messagingSenderId: '1044389536762',
    projectId: 'schedly-production',
    storageBucket: 'schedly-production.firebasestorage.app',
  );

  // NOTE: iOS app is not yet registered in schedly-production.
  // Register it at console.firebase.google.com → schedly-production → Add app → iOS
  // Then download GoogleService-Info.plist and replace these placeholder values.
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvHene63scD_yzJiR0HHWHBKTad-n-sSI', // placeholder: use iOS-specific key after registering
    appId: '1:1044389536762:ios:REPLACE_WITH_REAL_IOS_APP_ID',
    messagingSenderId: '1044389536762',
    projectId: 'schedly-production',
    storageBucket: 'schedly-production.firebasestorage.app',
    iosBundleId: 'com.example.schedly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvHene63scD_yzJiR0HHWHBKTad-n-sSI',
    appId: '1:1044389536762:ios:REPLACE_WITH_REAL_IOS_APP_ID',
    messagingSenderId: '1044389536762',
    projectId: 'schedly-production',
    storageBucket: 'schedly-production.firebasestorage.app',
    iosBundleId: 'com.example.schedly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvHene63scD_yzJiR0HHWHBKTad-n-sSI',
    appId: '1:1044389536762:web:8b8c7ec25645328411ba43',
    messagingSenderId: '1044389536762',
    projectId: 'schedly-production',
    authDomain: 'schedly-production.firebaseapp.com',
    storageBucket: 'schedly-production.firebasestorage.app',
    measurementId: 'G-RKCNHWHVX9',
  );
}
